import { IFile } from "../interfaces";

export const getDefaultRoutes = (): IFile => ({
  parent: null,
  icon: "root",
  id: "root",
  isFolder: true,
  name: "/",
  path: "/",
  appName: "folder",
  sortBy: "NAME",
  order: 0,
  createdOn: 0,
  updatedOn: 0,
  safe: true,
  files: {
    system: {
      parent: "/",
      icon: "system",
      id: "system",
      isFolder: true,
      name: "system",
      path: "/system",
      appName: "folder",
      files: {},
      safe: true,
      sortBy: "NAME",
      order: 1,
      createdOn: 0,
      updatedOn: 0,
    },
    applications: {
      parent: "/",
      icon: "applications",
      id: "applications",
      isFolder: true,
      name: "applications",
      path: "/applications",
      appName: "folder",
      files: {},
      safe: true,
      sortBy: "NAME",
      order: 2,
      createdOn: 0,
      updatedOn: 0,
    },
    users: {
      parent: "/",
      icon: "user",
      id: "users",
      isFolder: true,
      name: "users",
      path: "/users",
      appName: "folder",
      safe: true,
      sortBy: "NAME",
      order: 3,
      createdOn: 0,
      updatedOn: 0,
      files: {
        home: {
          parent: "/users",
          icon: "home",
          id: "home",
          isFolder: true,
          name: "${user}",
          path: "/users/${user}",
          appName: "folder",
          safe: true,
          sortBy: "NAME",
          order: 0,
          createdOn: 0,
          updatedOn: 0,
          files: {
            Pictures: {
              parent: "/users/${user}",
              icon: "pictures",
              id: "Pictures",
              isFolder: true,
              name: "Pictures",
              path: "/users/${user}/Pictures",
              appName: "folder",
              safe: true,
              files: {},
              sortBy: "NAME",
              order: 0,
              createdOn: 0,
              updatedOn: 0,
            },
            Documents: {
              parent: "/users/${user}",
              icon: "document",
              id: "Documents",
              isFolder: true,
              name: "Documents",
              path: "/users/${user}/Documents",
              appName: "folder",
              safe: true,
              files: {},
              sortBy: "NAME",
              order: 1,
              createdOn: 0,
              updatedOn: 0,
            },
            Downloads: {
              parent: "/users/${user}",
              icon: "download",
              id: "Downloads",
              isFolder: true,
              name: "Downloads",
              path: "/users/${user}/Downloads",
              appName: "folder",
              safe: true,
              files: {},
              sortBy: "NAME",
              order: 2,
              createdOn: 0,
              updatedOn: 0,
            },
            Desktop: {
              parent: "/users/${user}",
              icon: "desktop",
              id: "Desktop",
              isFolder: true,
              name: "Desktop",
              path: "/users/${user}/Desktop",
              appName: "folder",
              safe: true,
              sortBy: "NAME",
              order: 3,
              createdOn: 0,
              updatedOn: 0,
              files: {
                "Desktop 1": {
                  parent: "/users/${user}/Desktop",
                  icon: "folder",
                  id: "Desktop 1",
                  isFolder: true,
                  name: "Desktop 1",
                  path: "/users/${user}/Desktop/Desktop 1",
                  appName: "folder",
                  files: {},
                  sortBy: "NAME",
                  order: 0,
                  createdOn: 0,
                  updatedOn: 0,
                },
                "Desktop 2": {
                  parent: "/users/${user}/Desktop",
                  icon: "folder",
                  id: "Desktop 2",
                  isFolder: true,
                  name: "Desktop 2",
                  path: "/users/${user}/Desktop/Desktop 2",
                  appName: "folder",
                  files: {},
                  sortBy: "NAME",
                  order: 1,
                  createdOn: 0,
                  updatedOn: 0,
                },
              },
            },
          },
        },
      },
    },
  },
});
